---
stages:
- name: prepare
  cmd: python -m exp.iris.prepare
  deps:
    # either str either list of strings
    # "paths" because in some cases single arg may take
    # several values. For example "--dataset data1 data2 data3"
  - paths: data/raw/iris.data
    arg: "--dataset"
  outs:
  - paths: data/exp/iris/prepared.data
    arg: "--prepared"

- name: train
  cmd: python -m exp.iris.train
  deps:
  - paths: data/exp/iris/prepared.data
    arg: "--data"
  outs:
  - paths: data/exp/iris/checkpoint.txt
    arg: "--checkpoint"
  metrics:
  - paths: data/exp/iris/metrics.txt
    arg: "--metrics"
    cached: false
  # Any args passed to the script which are not deps, outs or metrics
  args:
    - "--epochs 100"

